// THIS FILE IS AUTOGENERATED. TO UPDATE, RUN
//    dart run tool/generate_asset_hashes.dart

const assetHashes = <String, String>{
  'fast_xlsx_windows_arm64.dll': 'c3ee0db6aff8f11c743dc32d7e545abb',
  'fast_xlsx_windows_x86_64.dll': '86392a5ce2b482d645a60022e66ca276',
  'libfast_xlsx_linux_aarch64.so': 'c5d1fc95835e8ec813f5f9b1ce1b5bab',
  'libfast_xlsx_linux_x86_64.so': 'c89369973c3470f5852fec4ed4121047',
  'libfast_xlsx_macos_arm64.dylib': 'fb0fc85a976310137337384c288d6767',
  'libfast_xlsx_macos_x86_64.dylib': '9f3d96b12d6a75a1139942d1d3c04272',
};
