// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:fast_xlsx/src/fast_xlsx_bindings.g.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ffi.Pointer<FxUploadHandle>>)>(
  symbol: 'fx_begin_upload',
)
external int _fx_begin_upload(
  ffi.Pointer<ffi.Pointer<FxUploadHandle>> out_handle,
);

FxStatus fx_begin_upload(ffi.Pointer<ffi.Pointer<FxUploadHandle>> out_handle) {
  return FxStatus.fromValue(_fx_begin_upload(out_handle));
}

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>)>()
external ffi.Pointer<ffi.Char> fx_error_message(ffi.Pointer<ffi.Void> handle);

@ffi.Native<ffi.Void Function(ffi.Pointer<FxOutputHandle>)>()
external void fx_output_close(ffi.Pointer<FxOutputHandle> handle);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<FxOutputHandle>,
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
    ffi.Pointer<ffi.UintPtr>,
  )
>(symbol: 'fx_output_read_chunk')
external int _fx_output_read_chunk(
  ffi.Pointer<FxOutputHandle> handle,
  ffi.Pointer<ffi.Uint8> buffer,
  int capacity,
  ffi.Pointer<ffi.UintPtr> out_len,
);

FxStatus fx_output_read_chunk(
  ffi.Pointer<FxOutputHandle> handle,
  ffi.Pointer<ffi.Uint8> buffer,
  int capacity,
  ffi.Pointer<ffi.UintPtr> out_len,
) {
  return FxStatus.fromValue(
    _fx_output_read_chunk(handle, buffer, capacity, out_len),
  );
}

@ffi.Native<ffi.Void Function(ffi.Pointer<FxReaderHandle>)>()
external void fx_reader_close(ffi.Pointer<FxReaderHandle> handle);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<FxReaderHandle>,
    ffi.Pointer<ffi.Pointer<FxRowHandle>>,
  )
>(symbol: 'fx_reader_next_row')
external int _fx_reader_next_row(
  ffi.Pointer<FxReaderHandle> handle,
  ffi.Pointer<ffi.Pointer<FxRowHandle>> out_row,
);

FxStatus fx_reader_next_row(
  ffi.Pointer<FxReaderHandle> handle,
  ffi.Pointer<ffi.Pointer<FxRowHandle>> out_row,
) {
  return FxStatus.fromValue(_fx_reader_next_row(handle, out_row));
}

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<FxReaderHandle>>,
  )
>(symbol: 'fx_reader_open_path')
external int _fx_reader_open_path(
  ffi.Pointer<ffi.Char> path,
  ffi.Pointer<ffi.Pointer<FxReaderHandle>> out_reader,
);

FxStatus fx_reader_open_path(
  ffi.Pointer<ffi.Char> path,
  ffi.Pointer<ffi.Pointer<FxReaderHandle>> out_reader,
) {
  return FxStatus.fromValue(_fx_reader_open_path(path, out_reader));
}

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
    ffi.Pointer<ffi.Pointer<FxReaderHandle>>,
  )
>(symbol: 'fx_reader_open_path_with_mode')
external int _fx_reader_open_path_with_mode(
  ffi.Pointer<ffi.Char> path,
  int mode,
  ffi.Pointer<ffi.Pointer<FxReaderHandle>> out_reader,
);

FxStatus fx_reader_open_path_with_mode(
  ffi.Pointer<ffi.Char> path,
  int mode,
  ffi.Pointer<ffi.Pointer<FxReaderHandle>> out_reader,
) {
  return FxStatus.fromValue(
    _fx_reader_open_path_with_mode(path, mode, out_reader),
  );
}

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<FxReaderHandle>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
  )
>(symbol: 'fx_reader_sheet_name')
external int _fx_reader_sheet_name(
  ffi.Pointer<FxReaderHandle> handle,
  ffi.Pointer<ffi.Pointer<ffi.Char>> out_name,
);

FxStatus fx_reader_sheet_name(
  ffi.Pointer<FxReaderHandle> handle,
  ffi.Pointer<ffi.Pointer<ffi.Char>> out_name,
) {
  return FxStatus.fromValue(_fx_reader_sheet_name(handle, out_name));
}

@ffi.Native<ffi.Bool Function(ffi.Pointer<FxRowHandle>, ffi.UintPtr)>()
external bool fx_row_cell_bool(ffi.Pointer<FxRowHandle> handle, int index);

@ffi.Native<ffi.Double Function(ffi.Pointer<FxRowHandle>, ffi.UintPtr)>()
external double fx_row_cell_double(ffi.Pointer<FxRowHandle> handle, int index);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<FxRowHandle>, ffi.UintPtr)>()
external int fx_row_cell_int(ffi.Pointer<FxRowHandle> handle, int index);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<FxRowHandle>, ffi.UintPtr)
>()
external ffi.Pointer<ffi.Char> fx_row_cell_string(
  ffi.Pointer<FxRowHandle> handle,
  int index,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<FxRowHandle>, ffi.UintPtr)>(
  symbol: 'fx_row_cell_type',
)
external int _fx_row_cell_type(ffi.Pointer<FxRowHandle> handle, int index);

FxCellType fx_row_cell_type(ffi.Pointer<FxRowHandle> handle, int index) {
  return FxCellType.fromValue(_fx_row_cell_type(handle, index));
}

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<FxRowHandle>)>()
external int fx_row_index(ffi.Pointer<FxRowHandle> handle);

@ffi.Native<ffi.UintPtr Function(ffi.Pointer<FxRowHandle>)>()
external int fx_row_len(ffi.Pointer<FxRowHandle> handle);

@ffi.Native<ffi.Void Function(ffi.Pointer<FxRowHandle>)>()
external void fx_row_release(ffi.Pointer<FxRowHandle> handle);

@ffi.Native<ffi.Void Function(ffi.Pointer<FxUploadHandle>)>()
external void fx_upload_close(ffi.Pointer<FxUploadHandle> handle);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<FxUploadHandle>,
    ffi.Pointer<ffi.Pointer<FxReaderHandle>>,
  )
>(symbol: 'fx_upload_finish_open_reader')
external int _fx_upload_finish_open_reader(
  ffi.Pointer<FxUploadHandle> handle,
  ffi.Pointer<ffi.Pointer<FxReaderHandle>> out_reader,
);

FxStatus fx_upload_finish_open_reader(
  ffi.Pointer<FxUploadHandle> handle,
  ffi.Pointer<ffi.Pointer<FxReaderHandle>> out_reader,
) {
  return FxStatus.fromValue(_fx_upload_finish_open_reader(handle, out_reader));
}

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<FxUploadHandle>,
    ffi.Uint32,
    ffi.Pointer<ffi.Pointer<FxReaderHandle>>,
  )
>(symbol: 'fx_upload_finish_open_reader_with_mode')
external int _fx_upload_finish_open_reader_with_mode(
  ffi.Pointer<FxUploadHandle> handle,
  int mode,
  ffi.Pointer<ffi.Pointer<FxReaderHandle>> out_reader,
);

FxStatus fx_upload_finish_open_reader_with_mode(
  ffi.Pointer<FxUploadHandle> handle,
  int mode,
  ffi.Pointer<ffi.Pointer<FxReaderHandle>> out_reader,
) {
  return FxStatus.fromValue(
    _fx_upload_finish_open_reader_with_mode(handle, mode, out_reader),
  );
}

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<FxUploadHandle>,
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
  )
>(symbol: 'fx_upload_write_chunk')
external int _fx_upload_write_chunk(
  ffi.Pointer<FxUploadHandle> handle,
  ffi.Pointer<ffi.Uint8> data,
  int len,
);

FxStatus fx_upload_write_chunk(
  ffi.Pointer<FxUploadHandle> handle,
  ffi.Pointer<ffi.Uint8> data,
  int len,
) {
  return FxStatus.fromValue(_fx_upload_write_chunk(handle, data, len));
}

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<FxWriterHandle>,
    ffi.Pointer<FxCellValue>,
    ffi.UintPtr,
  )
>(symbol: 'fx_writer_add_row')
external int _fx_writer_add_row(
  ffi.Pointer<FxWriterHandle> handle,
  ffi.Pointer<FxCellValue> cells,
  int len,
);

FxStatus fx_writer_add_row(
  ffi.Pointer<FxWriterHandle> handle,
  ffi.Pointer<FxCellValue> cells,
  int len,
) {
  return FxStatus.fromValue(_fx_writer_add_row(handle, cells, len));
}

@ffi.Native<ffi.Void Function(ffi.Pointer<FxWriterHandle>)>()
external void fx_writer_close(ffi.Pointer<FxWriterHandle> handle);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<FxWriterHandle>,
    ffi.Pointer<ffi.Pointer<FxOutputHandle>>,
  )
>(symbol: 'fx_writer_finish_open_output')
external int _fx_writer_finish_open_output(
  ffi.Pointer<FxWriterHandle> handle,
  ffi.Pointer<ffi.Pointer<FxOutputHandle>> out_output,
);

FxStatus fx_writer_finish_open_output(
  ffi.Pointer<FxWriterHandle> handle,
  ffi.Pointer<ffi.Pointer<FxOutputHandle>> out_output,
) {
  return FxStatus.fromValue(_fx_writer_finish_open_output(handle, out_output));
}

@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<FxWriterHandle>, ffi.Pointer<ffi.Char>)
>(symbol: 'fx_writer_finish_to_path')
external int _fx_writer_finish_to_path(
  ffi.Pointer<FxWriterHandle> handle,
  ffi.Pointer<ffi.Char> path,
);

FxStatus fx_writer_finish_to_path(
  ffi.Pointer<FxWriterHandle> handle,
  ffi.Pointer<ffi.Char> path,
) {
  return FxStatus.fromValue(_fx_writer_finish_to_path(handle, path));
}

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<FxWriterHandle>>,
  )
>(symbol: 'fx_writer_open')
external int _fx_writer_open(
  ffi.Pointer<ffi.Char> sheet_name,
  ffi.Pointer<ffi.Pointer<FxWriterHandle>> out_handle,
);

FxStatus fx_writer_open(
  ffi.Pointer<ffi.Char> sheet_name,
  ffi.Pointer<ffi.Pointer<FxWriterHandle>> out_handle,
) {
  return FxStatus.fromValue(_fx_writer_open(sheet_name, out_handle));
}

enum FxCellType {
  FX_CELL_BLANK(0),
  FX_CELL_INT(1),
  FX_CELL_DOUBLE(2),
  FX_CELL_BOOL(3),
  FX_CELL_TEXT(4),
  FX_CELL_DATE_TEXT(5),
  FX_CELL_ERROR(6);

  final int value;
  const FxCellType(this.value);

  static FxCellType fromValue(int value) => switch (value) {
    0 => FX_CELL_BLANK,
    1 => FX_CELL_INT,
    2 => FX_CELL_DOUBLE,
    3 => FX_CELL_BOOL,
    4 => FX_CELL_TEXT,
    5 => FX_CELL_DATE_TEXT,
    6 => FX_CELL_ERROR,
    _ => throw ArgumentError('Unknown value for FxCellType: $value'),
  };
}

final class FxCellValue extends ffi.Struct {
  @ffi.Uint32()
  external int cell_type;

  @ffi.Int64()
  external int int_value;

  @ffi.Double()
  external double double_value;

  @ffi.Bool()
  external bool bool_value;

  external ffi.Pointer<ffi.Char> string_value;

  static ffi.Pointer<FxCellValue> $allocate(
    ffi.Allocator $allocator, {
    required int cell_type,
    required int int_value,
    required double double_value,
    required bool bool_value,
    required ffi.Pointer<ffi.Char> string_value,
  }) => $allocator<FxCellValue>()
    ..ref.cell_type = cell_type
    ..ref.int_value = int_value
    ..ref.double_value = double_value
    ..ref.bool_value = bool_value
    ..ref.string_value = string_value;
}

final class FxOutputHandle extends ffi.Opaque {}

final class FxReaderHandle extends ffi.Opaque {}

enum FxReaderMode {
  FX_READER_MODE_STREAMING(0),
  FX_READER_MODE_BUFFERED(1);

  final int value;
  const FxReaderMode(this.value);

  static FxReaderMode fromValue(int value) => switch (value) {
    0 => FX_READER_MODE_STREAMING,
    1 => FX_READER_MODE_BUFFERED,
    _ => throw ArgumentError('Unknown value for FxReaderMode: $value'),
  };
}

final class FxRowHandle extends ffi.Opaque {}

enum FxStatus {
  FX_STATUS_OK(0),
  FX_STATUS_DONE(1),
  FX_STATUS_INVALID_ARGUMENT(2),
  FX_STATUS_IO_ERROR(3),
  FX_STATUS_XLSX_ERROR(4),
  FX_STATUS_UTF8_ERROR(5),
  FX_STATUS_INTERNAL_ERROR(6);

  final int value;
  const FxStatus(this.value);

  static FxStatus fromValue(int value) => switch (value) {
    0 => FX_STATUS_OK,
    1 => FX_STATUS_DONE,
    2 => FX_STATUS_INVALID_ARGUMENT,
    3 => FX_STATUS_IO_ERROR,
    4 => FX_STATUS_XLSX_ERROR,
    5 => FX_STATUS_UTF8_ERROR,
    6 => FX_STATUS_INTERNAL_ERROR,
    _ => throw ArgumentError('Unknown value for FxStatus: $value'),
  };
}

final class FxUploadHandle extends ffi.Opaque {}

final class FxWriterHandle extends ffi.Opaque {}
