import 'dart:io';

import 'package:args/args.dart';
import 'package:fast_xlsx/src/hook/download_asset.dart';
import 'package:fast_xlsx/src/hook/targets.dart';

Future<void> main(List<String> args) async {
  final parser = ArgParser()
    ..addOption(
      'assets-dir',
      help:
          'Use an existing directory of release assets instead of downloading.',
    );
  final argResults = parser.parse(args);
  final assetsDirOption = argResults.option('assets-dir');

  final assetsDir = assetsDirOption == null
      ? await _downloadAssets()
      : Directory(assetsDirOption);

  if (!await assetsDir.exists()) {
    throw StateError('Assets directory does not exist: ${assetsDir.path}');
  }

  final assetFiles =
      assetsDir.listSync(recursive: true).whereType<File>().toList()
        ..sort((left, right) => left.path.compareTo(right.path));

  final assetHashes = <String, String>{};
  for (final assetFile in assetFiles) {
    final fileHash = await hashAsset(assetFile);
    final fileName = assetFile.uri.pathSegments.lastWhere(
      (segment) => segment.isNotEmpty,
    );
    assetHashes[fileName] = fileHash;
  }

  await writeHashesFile(assetHashes);
}

Future<Directory> _downloadAssets() async {
  final assetsDir = Directory.fromUri(
    Platform.script.resolve('../.dart_tool/fast_xlsx/assets/'),
  );
  if (await assetsDir.exists()) {
    await assetsDir.delete(recursive: true);
  }
  await assetsDir.create(recursive: true);

  await Future.wait([
    for (final target in supportedTargets)
      downloadAsset(
        targetOS: target.os,
        targetArchitecture: target.architecture,
        outputDirectory: assetsDir,
      ),
  ]);

  return assetsDir;
}

Future<void> writeHashesFile(Map<String, String> assetHashes) async {
  final hashesFile = File.fromUri(
    Platform.script.resolve('../lib/src/hook/hashes.dart'),
  );
  await hashesFile.create(recursive: true);

  final buffer = StringBuffer();
  buffer.write('''
// THIS FILE IS AUTOGENERATED. TO UPDATE, RUN
//    dart run tool/generate_asset_hashes.dart

const assetHashes = <String, String>{
''');
  for (final entry in assetHashes.entries) {
    buffer.writeln("  '${entry.key}': '${entry.value}',");
  }
  buffer.write('''
};
''');

  await hashesFile.writeAsString(buffer.toString());
  await Process.run(Platform.executable, ['format', hashesFile.path]);
}
